spring:
  thymeleaf:
    mode: HTML
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myzoom?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 341282
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: info
    com.lins.myzoom: debug
  file:
    name: log/myzoom.blog
